insert into servicio (nombre, precio) values ("Manicure", 200);
insert into servicio (nombre, precio) values ("Geish en manos", 150);
insert into servicio (nombre, precio) values ("Gelish en pies", 200);
insert into servicio (nombre, precio) values ("Acrilicas", 400);
insert into servicio (nombre, precio) values ("Esculturales", 600);
insert into servicio (nombre, precio) values ("Diseño", 50);
insert into servicio (nombre, precio) values ("Set(efecto)", 150);
insert into servicio (nombre, precio) values ("Vitamina en uñas", 80);
insert into servicio (nombre, precio) values ("Retiro gelish", 50);
insert into servicio (nombre, precio) values ("Retiro acrilico", 100);
insert into servicio (nombre, precio) values ("Efectos(par)", 50);
insert into servicio (nombre, precio) values ("Diseño french", 200);
insert into servicio (nombre, precio) values ("Diseño en uña (par)", 50);
insert into servicio (nombre, precio) values ("Peinado y maquillaje", 1200);
insert into servicio (nombre, precio) values ("Maquillaje casual", 800);
insert into servicio (nombre, precio) values ("Peinado casual", 300);
insert into servicio (nombre, precio) values ("Peinado straight/wave", 200);
insert into servicio (nombre, precio) values ("Lavado", 200);
insert into servicio (nombre, precio) values ("Corte dama/niña", 300);
insert into servicio (nombre, precio) values ("Corte caballero/niño", 200);
insert into servicio (nombre, precio) values ("Balayage XL", 3400);
insert into servicio (nombre, precio) values ("Balayage L", 3000);
insert into servicio (nombre, precio) values ("Balayage M", 2400);
insert into servicio (nombre, precio) values ("Balayage S", 2000);
insert into servicio (nombre, precio) values ("Balayage XS", 1400);
insert into servicio (nombre, precio) values ("Nanoplastia XL", 3500);
insert into servicio (nombre, precio) values ("Nanoplastia L", 3000);
insert into servicio (nombre, precio) values ("Nanoplastia M", 2500);
insert into servicio (nombre, precio) values ("Nanoplastia S", 2000);
insert into servicio (nombre, precio) values ("Nanoplastia XS", 1500);
insert into servicio (nombre, precio) values ("Ampolleta", 200);
insert into servicio (nombre, precio) values ("Tratamiento Olaplex", 500);
insert into servicio (nombre, precio) values ("Tratamiento hidratacion intensiva", 500);
insert into servicio (nombre, precio) values ("Tinte XL", 3000);
insert into servicio (nombre, precio) values ("Tinte L", 2600);
insert into servicio (nombre, precio) values ("Tinte M", 2000);
insert into servicio (nombre, precio) values ("Tinte S", 1600);
insert into servicio (nombre, precio) values ("Tinte XS", 1100);
insert into servicio (nombre, precio) values ("Matiz XL", 3000);
insert into servicio (nombre, precio) values ("Matiz L", 2600);
insert into servicio (nombre, precio) values ("Matiz M", 2000);
insert into servicio (nombre, precio) values ("Matiz S", 1600);
insert into servicio (nombre, precio) values ("Matiz XS", 1100);
insert into servicio (nombre, precio) values ("Global XL", 1400);
insert into servicio (nombre, precio) values ("Global L", 1200);
insert into servicio (nombre, precio) values ("Global M", 1000);
insert into servicio (nombre, precio) values ("Global S", 800);
insert into servicio (nombre, precio) values ("Global XS", 600);